// biome-ignore-all format: generated
// This file is auto-generated by kitcn
// Do not edit manually. Run `kitcn codegen` to regenerate.

import { createApiLeaf, createGeneratedFunctionReference } from "kitcn/server";
import type { inferApiInputs, inferApiOutputs } from "kitcn/server";

import type { InferInsertModel, InferSelectModel } from "kitcn/orm";
import type { httpRouter } from "../functions/http";
import type { tables } from "../functions/schema";

export const api = {
  games: {
    control: {
      cashout: createApiLeaf<"mutation", typeof import("../functions/games/control").cashout>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/games/control").cashout>("games/control:cashout"), { auth: "required", type: "mutation" }),
      getOrStartSession: createApiLeaf<"mutation", typeof import("../functions/games/control").getOrStartSession>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/games/control").getOrStartSession>("games/control:getOrStartSession"), { auth: "required", type: "mutation" }),
      invest: createApiLeaf<"mutation", typeof import("../functions/games/control").invest>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/games/control").invest>("games/control:invest"), { auth: "required", type: "mutation" }),
    },
  },
  users: {
    me: createApiLeaf<"query", typeof import("../functions/users").me>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/users").me>("users:me"), { auth: "optional", type: "query" }),
  },
  http: undefined as unknown as typeof httpRouter,
  _http: {
  },
} as const;

export type Api = typeof api;
export type ApiInputs = inferApiInputs<Api>;
export type ApiOutputs = inferApiOutputs<Api>;

export type TableName = keyof typeof tables;
export type Select<T extends TableName> = InferSelectModel<(typeof tables)[T]>;
export type Insert<T extends TableName> = InferInsertModel<(typeof tables)[T]>;
